from os import getenv

SECRET_KEY = getenv("SECRET_KEY")
DB_NAME = getenv("SUPABASE_DB_NAME")
DB_USERNAME = getenv("SUPABASE_DB_USERNAME")
DB_PASSWORD = getenv("SUPABASE_DB_PASSWORD")
DB_HOST = getenv("SUPABASE_DB_HOST")
DB_PORT = getenv("SUPABASE_DB_PORT", "5432")
DATABASE_URI = getenv("SUPABASE_DB_URI")
SUPABASE_URL = getenv("SUPABASE_DB_URL")
SUPABASE_KEY = getenv("SUPABASE_SERVICE_KEY")
DEFAULT_PROFILE_URL = getenv("DEFAULT_PROFILE_URL")